name: Release Pipeline

on:
  workflow_dispatch:

jobs:
  Create-database-CI:
    environment: Dev
    name: Database-CI
    runs-on: ubuntu-latest
    permissions:
        pull-requests: write
        issues: write
        repository-projects: write
    steps:
      - name: Check out code
        uses: actions/checkout@v2

  Database-ci:
    needs: Create-database-CI
    name: Database CI
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Deploy database
        run: |
          echo "Running database deployment now"

  Database-Deploy-DEV:
    needs: Database-ci
    environment: DEV
    name: Database Deployment DEV
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Deploy database
        run: |
          echo "Running database deployment now"

  Database-Deploy-UAT:
    needs: Database-Deploy-DEV
    environment: UAT
    name: Database Deployment UAT
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Deploy database
        run: |
          echo "Running database deployment now"

  User-Input-Prod:
    needs: Database-Deploy-UAT
    runs-on: ubuntu-latest
    steps:
      - name: Request user input
        id: input
        uses: actions/github-script@v6
        with:
          script: |
            const response = await github.input('Do you want to deploy to PRODUCTION?', 'No', 'Yes');
            core.setOutput('deployToProd', response === 'Yes' ? 'true' : 'false')

 
  Database-Deploy-PROD:
    needs: User-Input-Prod
    environment: PROD
    name: Database Deployment PROD
    runs-on: ubuntu-latest
    if: ${{ needs.User-Input-Prod.outputs.deployToProd == 'true' }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: deploy database
        run: |
          echo "Running database deployment to PRODUCTION now"


  Database-Deploy-DR:
    needs: Database-Deploy-PROD
    environment: DR
    name: Database Deployment DR
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Deploy database
        run: |
          echo "Running database deployment now"
