name: Release Pipeline

on:
 workflow_dispatch:
   
jobs:
  Create-database-CI:
    environment: Dev
    name: Database-CI
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
      repository-projects: write


  Database-ci:
    needs: Create-database-CI
    name: Database CI
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: deploy database
        run: |
         echo " runing database deployment now "

  Database-Deploy-DEV:
    needs: Database-ci
    environment:  DEV
    name: Database Deployment DEV
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: deploy database
        run: |
         echo " runing database deployment now "
         
  Database-Deploy-UAT:
     needs: Database-Deploy-DEV
     environment: UAT
     name: Database Deployment UAT
     runs-on: ubuntu-latest
     steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: deploy database
        run: |
         echo " runing database deployment now "    

  Database-Deploy-PROD:
     needs: Database-Deploy-UAT
     environment: PROD
     name: Database Deployment PROD
     runs-on: ubuntu-latest
     steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: deploy database
        run: |
          echo "Please enter the PRODUCTION database password: "
          read -s DB_PASSWORD
          echo "::set-env name=DB_PASSWORD::$DB_PASSWORD"
          shell: bash
          echo " runing database deployment now "
          env:
            DB_PASSWORD: ${{ env.DB_PASSWORD }}
     

  Database-Deploy-DR:
     needs: Database-Deploy-PROD
     environment: DR
     name: Database Deployment DR
     runs-on: ubuntu-latest
     steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: deploy database
        run: |
         echo " runing database deployment now "         
