name: release
on:
  workflow_dispatch:
    inputs:
      app:
        type: boolean
        description: Deploy App
      database:
        type: boolean
        description: Deploy database
      releaseNo:
        type: text
        description: Version Number

jobs:

  create_release_branch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: 'refs/heads/Dev'
      
    - name: Create Release Branch
      run: |
        RELEASE_BRANCH_NAME=${{ github.event.inputs.Release }}
        git checkout -b $RELEASE_BRANCH_NAME Release
        git push --set-upstream origin Release
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
  
  app-deploy-dev:
     environment: DEV
     name: App  Deoloyment Dev
     if: ${{ github.event.inputs.app =='true' }}
     runs-on: ubuntu-latest
     steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: deploy App
        run: |
         echo " runing App deployment now "
  database-deploy-dev:
     environment: DEV
     name: Database  Deoloyment Dev
     if: ${{ github.event.inputs.database == 'true' }}
     runs-on: ubuntu-latest
     steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: deploy database
        run: |
         echo " runing database deployment now "
  app-deploy-uat:
     environment: UAT
     name: App  Deoloyment UAT
     if: ${{ github.event.inputs.app =='true' }}
     runs-on: ubuntu-latest
     needs: app-deploy-dev
     steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: deploy App
        run: |
         echo " runing App deployment now "
  database-deploy-uat:
     environment: UAT
     name: Database  Deoloyment UAT
     if: ${{ github.event.inputs.database == 'true' }}
     runs-on: ubuntu-latest
     needs: database-deploy-dev
     steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: deploy database
        run: |
         echo " runing database deployment now "
  app-deploy-PROD:
     environment: PROD
     name: App  Deoloyment PROD
     if: ${{ github.event.inputs.app =='true' }}
     runs-on: ubuntu-latest
     needs: app-deploy-uat
     steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: deploy App
        run: |
         echo " runing App deployment now "
  database-deploy-PROD:
     environment: PROD
     name: Database  Deoloyment PROD
     if: ${{ github.event.inputs.database == 'true' }}
     runs-on: ubuntu-latest
     needs: database-deploy-uat
     steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: deploy database
        run: |
         echo " runing database deployment now "
          
