name: Release Pipeline

on:
  workflow_dispatch:

jobs:
  Create-database-CI:
    environment: Dev
    name: Database-CI
    runs-on: ubuntu-latest
    permissions:
        pull-requests: write
        issues: write
        repository-projects: write
    steps:
      - name: Check out code
        uses: actions/checkout@v2

  Database-ci:
    needs: Create-database-CI
    name: Database CI
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Deploy database
        run: |
          echo "Running database deployment now"

  Database-Deploy-DEV:
    needs: Database-ci
    environment: DEV
    name: Database Deployment DEV
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Deploy database
        run: |
          echo "Running database deployment now"

  Database-Deploy-UAT:
    needs: Database-Deploy-DEV
    environment: UAT
    name: Database Deployment UAT
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Deploy database
        run: |
          echo "Running database deployment now"

  Database-Deploy-PROD:
    needs: Database-Deploy-UAT
    environment: PROD
    name: Database Deployment PROD
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Prompt for DB password
        run: |
          echo "Please enter the PRODUCTION database password: "
          read -s DB_PASSWORD
          echo "DB_PASSWORD=${DB_PASSWORD}" >> $GITHUB_ENV
        
      - name: Deploy database
        run: |
          echo "Running database deployment now"
        env:
          DB_PASSWORD: ${{ env.DB_PASSWORD }}


  Database-Deploy-DR:
    needs: Database-Deploy-PROD
    environment: DR
    name: Database Deployment DR
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Deploy database
        run: |
          echo "Running database deployment now"
