name: Release Pipeline

on:
  workflow_dispatch:

jobs:
  Create-database-CI:
    environment: Dev
    name: Database-CI
    runs-on: ubuntu-latest
    permissions:
        pull-requests: write
        issues: write
        repository-projects: write
    steps:
      - name: Check out code
        uses: actions/checkout@v2

  Database-Deploy-PROD:
    name: Database Deployment PROD
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Prompt for DB password
        run: |
          echo "Please enter the PRODUCTION database password: "
          read -r DB_PASSWORD
          echo "DB_PASSWORD=$DB_PASSWORD" >> $GITHUB_ENV
          shell: bash
        
