name: release
run-name: release - ${{github.event.inputs.releaseNo}}
on:
  workflow_dispatch:
    inputs:
      app:
        type: boolean
        description: Deploy App
      database:
        type: boolean
        description: Deploy database
      releaseNo:
        type: string
        description: Version Number

env:
  Workflow2_PAT_TOKEN_GITHUB: "${{ secrets.Workflow2_PAT_TOKEN_GITHUB }}"  
  GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
  #RELEASE_BRANCH_NAME: ''

jobs:

  create-app-ci:
    if: ${{ github.event.inputs.app =='true' }}
    environment: Dev
    name: APP CI DEV
    runs-on: ubuntu-latest
    permissions:
        pull-requests: write
        issues: write
        repository-projects: write
    
    steps:
    - name: Checkout App Code
      uses: actions/checkout@v3
      with:
        repository: lf-retail/app-service
        ref: 'refs/heads/Dev' 
        token: ${{ secrets.PAT_TOKEN }}
    - name : Create Release Branch 
      run: |
        RELEASE_BRANCH_NAME=release/r-${{ github.event.inputs.releaseNo }}
        git checkout -b $RELEASE_BRANCH_NAME
        git push --set-upstream origin $RELEASE_BRANCH_NAME
      env:
        token: $GITHUB_TOKEN
        Workflow2_PAT_TOKEN_GITHUB: $Workflow2_PAT_TOKEN_GITHUB

  app-CI-dev:
    needs: create-app-ci
    uses: lf-common-repo/shared-workflow/.github/workflows/java-maven-sonar-ci.yml@main
    with:
      repoName: "lf-retail/app-service"
      branchName: $RELEASE_BRANCH_NAME
    secrets:
      token: $GITHUB_TOKEN
      Workflow2_PAT_TOKEN_GITHUB: $Workflow2_PAT_TOKEN_GITHUB 
      
  create-database-ci:
    if: ${{ github.event.inputs.database == 'true' }}
    environment: Dev
    name: Database CI DEV
    runs-on: ubuntu-latest
    permissions:
        pull-requests: write
        issues: write
        repository-projects: write
    
    steps:
    - name: Checkout App Code
      uses: actions/checkout@v3
      with:
        repository: lf-retail/app-service
        ref: 'refs/heads/Dev' 
        token: ${{ secrets.PAT_TOKEN }}
    - name : Create Release Branch 
      run: |
        RELEASE_BRANCH_NAME=release/r-${{ github.event.inputs.releaseNo }}
        git checkout -b $RELEASE_BRANCH_NAME
        git push --set-upstream origin $RELEASE_BRANCH_NAME
      env:
        token: $GITHUB_TOKEN
        Workflow2_PAT_TOKEN_GITHUB: $Workflow2_PAT_TOKEN_GITHUB      
  
  database-CI-dev:
    
    needs: create-database-ci
    uses: lf-common-repo/shared-workflow/.github/workflows/databaseci.yml@main
    with:
      repoName: "lf-retail/app-service"
      branchName: $RELEASE_BRANCH_NAME
    secrets:
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}       
      token: $GITHUB_TOKEN
      Workflow2_PAT_TOKEN_GITHUB: $Workflow2_PAT_TOKEN_GITHUB
