name: release
run-name: release - ${{ github.event.inputs.releaseNo }}
on:
  workflow_dispatch:
    inputs:
      app:
        type: boolean
        description: Deploy App
      database:
        type: boolean
        description: Deploy database
      releaseNo:
        type: string
        description: Version Number

env:
  Workflow2_PAT_TOKEN_GITHUB: "${{ secrets.Workflow2_PAT_TOKEN_GITHUB }}"  
  GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
  #RELEASE_BRANCH_NAME: ''

jobs:

  CI-BUILD-FOR-APP:
    name: Application CI DEV
    if: ${{ github.event.inputs.app =='true' }}
    runs-on: ubuntu-latest
    permissions:
        pull-requests: write
        issues: write
        repository-projects: write
    
    steps:
    - name: Checkout App Code
      uses: actions/checkout@v3
      with:
        repository: lf-retail/app-service
        ref: 'refs/heads/Dev' 
        token: ${{ secrets.PAT_TOKEN }}
    - name : Create Release Branch 
      run: |
        RELEASE_BRANCH_NAME=release/r-${{ github.event.inputs.releaseNo }}
        git checkout -b $RELEASE_BRANCH_NAME
        git push --set-upstream origin $RELEASE_BRANCH_NAME
      env:
        token: $GITHUB_TOKEN
        Workflow2_PAT_TOKEN_GITHUB: $Workflow2_PAT_TOKEN_GITHUB
    - name: Call reusable workflow
      uses: lf-common-repo/shared-workflow/github/workflows/java-maven-sonar-ci.yml@main
      with:
        repoName: "lf-retail/app-service"
        branchName: $RELEASE_BRANCH_NAME
      env:
        token: $GITHUB_TOKEN
        Workflow2_PAT_TOKEN_GITHUB: $Workflow2_PAT_TOKEN_GITHUB 
