name: Release Pipeline

on:
  workflow_dispatch:

jobs:
  Create-database-CI:
    environment: Dev
    name: Database-CI
    runs-on: ubuntu-latest
    permissions:
        pull-requests: write
        issues: write
        repository-projects: write
    steps:
      - name: Check out code
        uses: actions/checkout@v2

  Database-ci:
    needs: Create-database-CI
    name: Database CI
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Deploy database
        run: |
          echo "Running database deployment now"

  Database-Deploy-DEV:
    needs: Database-ci
    environment: DEV
    name: Database Deployment DEV
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Deploy database
        run: |
          echo "Running database deployment now"

  Database-Deploy-UAT:
    needs: Database-Deploy-DEV
    environment: UAT
    name: Database Deployment UAT
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Deploy database
        run: |
          echo "Running database deployment now"

  User-Input-Prod:
    needs: Database-Deploy-UAT
    runs-on: ubuntu-latest
    steps:
      - name: Create Comment for User Input
        uses: actions/github-script@v5
        with:
          script: |
            const issueComment = `@${github.context.actor} Do you want to deploy to PRODUCTION? (Reply with 'Yes' or 'No')`;
            github.issues.createComment({ issue_number: github.context.issue.number, owner: github.context.repo.owner, repo: github.context.repo.repo, body: issueComment });
 
  Database-Deploy-PROD:
    needs: User-Input-Prod
    environment: PROD
    name: Database Deployment PROD
    runs-on: ubuntu-latest
    if: ${{ needs.User-Input-Prod.outputs.deployToProd == 'true' }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: deploy database
        run: |
          echo "Running database deployment to PRODUCTION now"


  Database-Deploy-DR:
    needs: Database-Deploy-PROD
    environment: DR
    name: Database Deployment DR
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Deploy database
        run: |
          echo "Running database deployment now"
