name: Check Main Branch for Hotfix/Bug Fix and Branch Sync

on:
  workflow_dispatch

jobs:
  check-main-branch:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: Check for Hotfix/Bug Fix in Main Branch
      run: |
        git fetch origin main
        CHANGED_COMMITS=$(git log --oneline origin/main..Dev | grep -iE 'hotfix|bug fix' || true)
        if [ -n "$CHANGED_COMMITS" ]; then
          echo "Commits with 'hotfix' or 'bug fix' keywords found in main branch."
          exit 1
        fi
    - name: Check Branch Sync
      run: |
        git fetch origin main
        BEHIND_COMMITS=$(git rev-list --count Dev..origin/main)
        if [ "$BEHIND_COMMITS" -gt 0 ]; then
          echo "Dev branch is $BEHIND_COMMITS commits behind the main branch."
          exit 1
        fi
